apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy48
  labels:
    app: autodeploy48
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718787479787
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy48
  template:
    metadata:
      labels:
        app: autodeploy48
    spec:
      containers:
        - name: autodeploy48
          image: acrworkflow1718787479787.azurecr.io/image-workflow-1718787479787:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
