apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy88
  labels:
    app: autodeploy88
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1718791003636
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy88
  template:
    metadata:
      labels:
        app: autodeploy88
    spec:
      containers:
        - name: autodeploy88
          image: acrworkflow1718791003636.azurecr.io/image-workflow-1718791003636:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
