apiVersion: v1
kind: Service
metadata:
  name: autodeploy48
  namespace: namespace-workflow-1718787479787
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy48
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000